import type { Metadata } from "next";
import { Inter } from "next/font/google";
import styles from "./style.module.scss";
import classNames from "classnames";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={classNames(inter.className, styles.body)}>
        {children}
      </body>
    </html>
  );
}
