version: "3"
services:
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    command: yarn dev
    volumes:
      - ./frontend:/frontend
    ports:
      - 3000:3000
    tty: true
