name: check-frontend
on:
  pull_request:
    paths:
      - "frontend/**"
jobs:
  check:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: frontend

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.17.1"

      - name: Install Dependencies
        run: yarn install

      - name: Check Format
        run: yarn format:check

      - name: Check Lint
        run: yarn lint:check

      - name: Check Stylelint
        run: yarn stylelint:check

      - name: Run Test
        run: yarn test --ci --colors
